[project]
name = "my-portfolio-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest",
    "flake8",
    "asyncio",
    "python-dotenv",
    "PyGithub"
]
